services:
  lb:
    build: .
    ports:
      - "9999:9999"
    environment:
      - DATA_DIR=/data
      - PORT=9999
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9999/ready"]
      interval: 2s
      timeout: 2s
      retries: 60
      start_period: 180s
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "338MB"
    networks:
      - rinha

  api-1:
    image: alpine:latest
    command: sleep infinity
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "6MB"
    networks:
      - rinha

  api-2:
    image: alpine:latest
    command: sleep infinity
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "6MB"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge
